.github/workflows/ci.yml
.github/workflows/lock.yml
.github/workflows/needs-reply-remove.yml
.github/workflows/needs-reply.yml
.github/workflows/needs-triage.yml
.github/workflows/package-label.yml
.github/workflows/release.yml

ci: add gh workflows

---

packages/barcode-scanning/README.md

docs(barcode-scanning): fix typo

---

.changeset/polite-falcons-compete.md
.prettierrc.js
package-lock.json
packages/barcode-scanning/.prettierrc.js
packages/barcode-scanning/BREAKING.md
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScanner.java
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScannerHelper.java
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScannerPlugin.java
packages/barcode-scanning/ios/Plugin/BarcodeScanner.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerHelper.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerPlugin.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift
packages/barcode-scanning/package.json
packages/translation/.prettierrc.js
packages/translation/package.json

fix(barcode-scanning)!: improve `cornerPoints` calculation

---

.changeset/late-maps-beg.md
packages/barcode-scanning/CapacitorMlkitBarcodeScanning.podspec
packages/barcode-scanning/ios/Podfile
packages/translation/CapacitorMlkitTranslation.podspec
packages/translation/ios/Podfile

fix(ios): Cocoapods dependency conflicts with Firebase

---

.changeset/nine-buckets-argue.md
packages/barcode-scanning/ios/Plugin/BarcodeScanner.swift

Add a missing completion() call on successful startScan()
Close #48

fix(barcode-scanning): resolve the `startScan(...)` method (#50)

---

.changeset/popular-rings-fetch.md
packages/barcode-scanning/README.md
packages/barcode-scanning/android/build.gradle
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScanner.java
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScannerPlugin.java
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/InstallGoogleBarcodeScannerModuleResultCallback.java
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/IsGoogleBarodeScannerModuleAvailableResultCallback.java
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/ModuleInstallProgressListener.java
packages/barcode-scanning/ios/Plugin/BarcodeScannerPlugin.m
packages/barcode-scanning/ios/Plugin/BarcodeScannerPlugin.swift
packages/barcode-scanning/src/definitions.ts
packages/barcode-scanning/src/web.ts

Close #38 
See https://developers.google.com/android/guides/module-install-apis

fix(barcode-scanning): `scan failed` on some Android devices

---

package-lock.json
packages/selfie-segmentation/README.md
packages/selfie-segmentation/src/definitions.ts
packages/selfie-segmentation/src/web.ts

feat: add @capacitor-mlkit/selfie-segmentation package

---

.changeset/cool-beds-cheat.md
packages/barcode-scanning/ios/Plugin/BarcodeScanner.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerHelper.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerPlugin.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift

fix(barcode-scanning): incorrect coordinate calculation in landscape mode on iOS

---

.changeset/eight-dancers-sniff.md
packages/barcode-scanning/BREAKING.md
packages/barcode-scanning/android/build.gradle
packages/face-detection/BREAKING.md
packages/face-detection/android/build.gradle
packages/face-mesh-detection/BREAKING.md
packages/face-mesh-detection/android/build.gradle
packages/selfie-segmentation/BREAKING.md
packages/selfie-segmentation/android/build.gradle
packages/translation/BREAKING.md
packages/translation/android/build.gradle

chore(deps)!: update Android SDKs

---

.changeset/hungry-glasses-push.md
packages/barcode-scanning/README.md
packages/barcode-scanning/android/build.gradle

fix(barcode-scanning): enable the databinding library on Android

---

.changeset/purple-seahorses-switch.md
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/ModuleInstallProgressListener.java

fix(barcode-scanning): invalid `progress` values

---

.changeset/afraid-otters-joke.md
packages/barcode-scanning/CapacitorMlkitBarcodeScanning.podspec
packages/barcode-scanning/ios/Podfile
packages/face-detection/CapacitorMlkitFaceDetection.podspec
packages/face-detection/ios/Podfile
packages/selfie-segmentation/CapacitorMlkitSelfieSegmentation.podspec
packages/selfie-segmentation/ios/Podfile
packages/translation/CapacitorMlkitTranslation.podspec
packages/translation/ios/Podfile

feat(ios): update `GoogleMLKit` dependencies to `5.0.0`

---

packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScannerPlugin.java

chore(barcode-scanning): update error message for missing Google Barcode Scanner Module

---

.changeset/chilled-dodos-dream.md
packages/barcode-scanning/README.md
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScanner.java
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScannerPlugin.java
packages/barcode-scanning/ios/Plugin/BarcodeScanner.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerHelper.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerPlugin.swift
packages/barcode-scanning/src/definitions.ts

feat(barcode-scanning): add `barcodesScanned` listener

---

.changeset/stupid-trains-change.md
packages/barcode-scanning/src/definitions.ts

Close https://github.com/robingenz/capacitor-mlkit-plugin-demo/issues/27

fix(barcode-scanning): remove deprecated warnings for torch methods

---

.changeset/violet-coats-act.md
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScanner.java
packages/barcode-scanning/src/definitions.ts

Related to https://github.com/capawesome-team/capacitor-plugins/issues/333

feat(barcode-scanning): add compatibility for the Torch plugin

---

.changeset/angry-pugs-deliver.md
packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift

fix(barcode-scanning): resize the barcode scanner view when the device orientation changes

---

.changeset/rotten-trains-obey.md
packages/barcode-scanning/BREAKING.md
packages/barcode-scanning/README.md
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScanner.java
packages/barcode-scanning/android/src/main/java/io/capawesome/capacitorjs/plugins/mlkit/barcodescanning/BarcodeScannerPlugin.java
packages/barcode-scanning/ios/Plugin/BarcodeScanner.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerPlugin.m
packages/barcode-scanning/ios/Plugin/BarcodeScannerPlugin.swift
packages/barcode-scanning/src/definitions.ts
packages/barcode-scanning/src/web.ts

refactor!: remove deprecated code

---

.changeset/wet-crabs-share.md
packages/barcode-scanning/BREAKING.md
packages/barcode-scanning/README.md
packages/barcode-scanning/android/build.gradle
packages/barcode-scanning/ios/Plugin/BarcodeScanner.swift
packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift
packages/face-detection/BREAKING.md
packages/face-detection/README.md
packages/face-detection/android/build.gradle
packages/selfie-segmentation/BREAKING.md
packages/selfie-segmentation/README.md
packages/selfie-segmentation/android/build.gradle
packages/translation/BREAKING.md
packages/translation/README.md
packages/translation/android/build.gradle

chore: update native dependencies

---

.changeset/two-candles-sing.md
packages/barcode-scanning/README.md
packages/barcode-scanning/src/barcode-detector.d.ts
packages/barcode-scanning/src/definitions.ts
packages/barcode-scanning/src/web.ts

Close #20 
This PR is based on #211.

feat(barcode-scanning): add web support

---

.changeset/twelve-walls-doubt.md
packages/barcode-scanning/ios/Plugin/BarcodeScannerView.swift

fix(barcode-scanning): `resolution` option was ignored on iOS
